from PySide6.QtCore import QCoreApplication


def translate_ui(self, main_window, language):
    if language == 'en-US':
        main_window.setWindowTitle(QCoreApplication.translate("MainWindow", u"Alt PDF", None))

        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open...", None))
        self.actionSave_Page_As_Image.setText(QCoreApplication.translate("MainWindow", u"Save pages as image.", None))
        self.actionCompress.setText(QCoreApplication.translate("MainWindow", u"Compress...", None))
        self.actionPasswordDoc.setText(QCoreApplication.translate("MainWindow", u"Password...", None))
        self.actionSaveAs.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
        self.actionAddFile.setText(QCoreApplication.translate("MainWindow", u"Add File...", None))
        self.actionAboutPdf.setText(QCoreApplication.translate("MainWindow", u"About PDF...", None))
        self.actionClosePdf.setText(QCoreApplication.translate("MainWindow", u"Close PDF", None))
        self.actionJumpToFirstPage.setText(QCoreApplication.translate("MainWindow", u"Jump to First Page", None))
        self.actionJumpToLastPage.setText(QCoreApplication.translate("MainWindow", u"Jump to Last Page", None))
        self.actionEnumeratePages.setText(QCoreApplication.translate("MainWindow", u"Enumerate Pages", None))
        self.actionFitToWidth.setText(QCoreApplication.translate("MainWindow", u"Fit to page width", None))
        self.actionFitToHeight.setText(QCoreApplication.translate("MainWindow", u"Fit to page height", None))
        self.menuRotation.setTitle(QCoreApplication.translate("MainWindow", u"Viewer rotation...", None))
        self.menuNavigation.setTitle(QCoreApplication.translate("MainWindow", u"Page navigation...", None))
        self.menuZoom.setTitle(QCoreApplication.translate("MainWindow", u"Viewer zoom...", None))
        self.actionRotateViewClockwise.setText(QCoreApplication.translate("MainWindow", u"Rotate viewer clockwise", None))
        self.actionRotateViewCounterclockwise.setText(QCoreApplication.translate("MainWindow", u"Rotate viewer counterclockwise", None))
        self.actionRotateCurrentPageClockwise.setText(QCoreApplication.translate("MainWindow", u"Rotate page clockwise", None))
        self.actionRotateCurrentPageCounterclockwise.setText(QCoreApplication.translate("MainWindow", u"Rotate page counterclockwise", None))
        self.actionRotateSpecificPages.setText(QCoreApplication.translate("MainWindow", u"Rotate pages...", None))
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Print...", None))
        self.actionEmail.setText(QCoreApplication.translate("MainWindow", u"Send via email...", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save document", None))
        self.actionDeletePage.setText(QCoreApplication.translate("MainWindow", u"Delete current page", None))
        self.actionDeleteSpecificPages.setText(QCoreApplication.translate("MainWindow", u"Delete pages...", None))
        self.actionMovePageDown.setText(QCoreApplication.translate("MainWindow", u"Move page down", None))
        self.actionMovePageUp.setText(QCoreApplication.translate("MainWindow", u"Move page up", None))
        self.actionDraw.setText(QCoreApplication.translate("MainWindow", u"Drawing toools", None))

        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionZoom_In.setText(QCoreApplication.translate("MainWindow", u"Zoom In", None))
        self.actionZoom_Out.setText(QCoreApplication.translate("MainWindow", u"Zoom Out", None))
        self.actionPrevious_Page.setText(QCoreApplication.translate("MainWindow", u"Previous Page", None))
        self.actionNext_Page.setText(QCoreApplication.translate("MainWindow", u"Next Page", None))

        self.actionToggle_Panel.setText(QCoreApplication.translate("MainWindow", u"Toggle Sidepanel", None))

        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))

    if language == 'ru-RU':
        main_window.setWindowTitle(QCoreApplication.translate("MainWindow", u"Альт PDF", None))

        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Открыть...", None))

        self.actionSave_Page_As_Image.setText(QCoreApplication.translate("MainWindow", u"Сохранить страницы как изображения...", None))
        self.actionCompress.setText(QCoreApplication.translate("MainWindow", u"Сжать...", None))
        self.actionPasswordDoc.setText(QCoreApplication.translate("MainWindow", u"Защита паролем...", None))
        self.actionSaveAs.setText(QCoreApplication.translate("MainWindow", u"Сохранить как...", None))
        self.actionAddFile.setText(QCoreApplication.translate("MainWindow", u"Добавить файл...", None))
        self.actionAboutPdf.setText(QCoreApplication.translate("MainWindow", u"О pdf-документе...", None))
        self.actionClosePdf.setText(QCoreApplication.translate("MainWindow", u"Закрыть pdf-документ", None))
        self.actionJumpToFirstPage.setText(QCoreApplication.translate("MainWindow", u"Первая страница", None))
        self.actionJumpToLastPage.setText(QCoreApplication.translate("MainWindow", u"Последняя страница", None))
        self.actionEnumeratePages.setText(QCoreApplication.translate("MainWindow", u"Пронумеровать страницы...", None))
        self.actionFitToWidth.setText(QCoreApplication.translate("MainWindow", u"По ширине", None))
        self.actionFitToHeight.setText(QCoreApplication.translate("MainWindow", u"По высоте", None))
        self.menuRotation.setTitle(QCoreApplication.translate("MainWindow", u"Поворот вида...", None))
        self.menuNavigation.setTitle(QCoreApplication.translate("MainWindow", u"Навигация по страницам...", None))
        self.menuZoom.setTitle(QCoreApplication.translate("MainWindow", u"Масштаб просмотра...", None))
        self.actionRotateViewClockwise.setText(QCoreApplication.translate("MainWindow", u"По часовой стрелке", None))
        self.actionRotateViewCounterclockwise.setText(QCoreApplication.translate("MainWindow", u"Против часовой стрелки", None))
        self.actionRotateCurrentPageClockwise.setText(QCoreApplication.translate("MainWindow", u"Повернуть страницу по часовой стрелке", None))
        self.actionRotateCurrentPageCounterclockwise.setText(QCoreApplication.translate("MainWindow", u"Повернуть страницу против часовой стрелки", None))
        self.actionRotateSpecificPages.setText(QCoreApplication.translate("MainWindow", u"Повернуть страницы...", None))
        self.actionPrint.setText(QCoreApplication.translate("MainWindow", u"Печать...", None))
        self.actionEmail.setText(QCoreApplication.translate("MainWindow", u" Отправить по почте...", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Сохранить", None))
        self.actionDeletePage.setText(QCoreApplication.translate("MainWindow", u"Удалить текущую страницу", None))
        self.actionDeleteSpecificPages.setText(QCoreApplication.translate("MainWindow", u"Удалить страницы...", None))
        self.actionMovePageDown.setText(QCoreApplication.translate("MainWindow", u"Переместить страницу вниз", None))
        self.actionMovePageUp.setText(QCoreApplication.translate("MainWindow", u"Переместить страницу вверх", None))
        self.actionDraw.setText(QCoreApplication.translate("MainWindow", u"Инструменты рисования", None))

        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Выход", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"О программе", None))
        self.actionZoom_In.setText(QCoreApplication.translate("MainWindow", u"Приблизить", None))
        self.actionZoom_Out.setText(QCoreApplication.translate("MainWindow", u"Отдалить", None))
        self.actionPrevious_Page.setText(QCoreApplication.translate("MainWindow", u"Предыдущая страница", None))
        self.actionNext_Page.setText(QCoreApplication.translate("MainWindow", u"Следующая страница", None))

        self.actionToggle_Panel.setText(QCoreApplication.translate("MainWindow", u"Боковая панель", None))

        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"Файл", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"Просмотр", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Редактирование", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Справка", None))


def shortcuts_ui(self):
    self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
    self.actionSaveAs.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
    self.actionPasswordDoc.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+P", None))
    self.actionCompress.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+J", None))
    self.actionSave_Page_As_Image.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+A", None))
    self.actionPasswordDoc.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+P", None))
    self.actionAddFile.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+O", None))
    self.actionAboutPdf.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
    self.actionClosePdf.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+W", None))
    self.actionJumpToFirstPage.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Home", None))
    self.actionJumpToLastPage.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+End", None))
    self.actionEnumeratePages.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
    self.actionFitToWidth.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+W", None))
    self.actionFitToHeight.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+H", None))
    self.actionRotateViewClockwise.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+R", None))
    self.actionRotateViewCounterclockwise.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+L", None))
    self.actionRotateCurrentPageClockwise.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
    self.actionRotateCurrentPageCounterclockwise.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+L", None))
    self.actionRotateSpecificPages.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+R", None))
    self.actionPrint.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+P", None))
    self.actionEmail.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+E", None))
    self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
    self.actionDeletePage.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+D", None))
    self.actionDeleteSpecificPages.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+D", None))
    self.actionMovePageDown.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+Down", None))
    self.actionMovePageUp.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+Up", None))
    self.actionDraw.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+D", None))
    self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
    self.actionAbout.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+I", None))
    self.actionZoom_In.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+=", None))
    self.actionZoom_Out.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
    self.actionPrevious_Page.setShortcut(QCoreApplication.translate("MainWindow", u"PgUp", None))
    self.actionNext_Page.setShortcut(QCoreApplication.translate("MainWindow", u"PgDown", None))
    self.actionToggle_Panel.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+G", None))


def define_labels(self, language):
    pass
